server:
  port: 30430
spring:
  application:
    name: easy-service-system
  config:
    import:
      - optional:application-datasource.yml
      - optional:application-web.yml
      - optional:application-token.yml
      - optional:application-redis.yml
      - optional:application-dubbo.yml
  profiles:
    active: dev

mybatis-plus:
  mapper-package: com.easy.**.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.easy.system
# knife4j的增强配置，不需要增强可以不配
knife4j:
  documents:
    - group: default
      name: 系统服务

dubbo:
  application:
    qos-port: 23334
  scan:
    # 接口实现类扫描
    base-packages: com.easy.**.service